export const SET_MAIN_NAVIGATION = "set_main_navigation";
export const SAVE_MULTIPLE_POST_JOB_SCREENS_STATE =
  "SAVE_MULTIPLE_POST_JOB_SCREENS_STATE";

export const REMOVE_SELECTED_EXTRA_QUESTION = "REMOVE_SELECTED_EXTRA_QUESTION";

export const DELETE_MULTIPLE_POST_JOB_SCREENS_STATE =
  "DELETE_MULTIPLE_POST_JOB_SCREENS_STATE";

export const STORE_GEO_LOCATION = "STORE_GEO_LOCATION";
